version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "5432:5432"
    volumes:
      - "nestjs-mysql:/data/mysql"
    env_file:
      - docker.env
    networks:
      - mysql
volumes:
  nestjs-mysql:
networks:
  mysql:
    driver: bridge
